server:
  address:     ":6020"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  clientMaxBodySize: 1024 * 1024 * 1024 * 1024 * 1024 * 1024 * 1024 * 1024 * 1024 * 1024 * 1024 * 1024 * 1024 * 1024
  accessLogEnabled: true
  accessLogPattern: "access-{Ymd}.log"
  logPath: "./resource/logs/gf"

logger:
  level : "all"
  stdout: true



