server:
  address:     ":6020"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  clientMaxBodySize: 1024 * 1024 * 1024 * 1024 * 1024 * 1024 * 1024 * 1024 * 1024 * 1024 * 1024 * 1024 * 1024 * 1024

logger:
  level : "all"
  stdout: true



